services:
  - type: web
    name: stableflow-api
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /api/v1/health 